/*
 * SPDX-License-Identifier: LicenseRef-SlabFlux-Source-Available
 *
 * ============================================================================
 * SLABFLUX SOFTWARE ENGINE
 * Copyright (c) 2026 Kristóf Barta (https://github.com/kbartadev)
 * ============================================================================
 * SOURCE-AVAILABLE CODEBASE
 *
 * This source file is distributed under the conditions of the SLABFLUX 
 * SOURCE-AVAILABLE AND ECOSYSTEM LICENSE (the "License").
 *
 * ----------------------------------------------------------------------------
 * CRITICAL WARNING
 * ----------------------------------------------------------------------------
 * This module may execute outside standard OS mediation layers. Incorrect 
 * integration, misconfiguration, or unsafe deployment can result in:
 *
 *   • irreversible data corruption
 *   • kernel instability or panics
 *   • NIC or PCIe bus desynchronization
 *   • undefined hardware state transitions
 *   • permanent loss of system integrity
 *
 * Use only in controlled environments with full understanding of the 
 * architectural constraints and hardware implications.
 *
 * ----------------------------------------------------------------------------
 * USAGE GUIDELINES
 * ----------------------------------------------------------------------------
 * Execution, integration, and deployment by developers is permitted strictly 
 * subject to the conditional grants and structural limitations defined within 
 * the License. Please refer to the License for full terms regarding corporate 
 * deployment and replication.
 *
 * ----------------------------------------------------------------------------
 * LIMITATION OF LIABILITY
 * ----------------------------------------------------------------------------
 * TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL THE AUTHOR OR 
 * COPYRIGHT HOLDER BE LIABLE FOR ANY CLAIM, DAMAGES, OR OTHER LIABILITY, 
 * WHETHER IN AN ACTION OF CONTRACT, TORT, OR OTHERWISE, ARISING FROM, OUT OF, 
 * OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 *
 * ----------------------------------------------------------------------------
 * DISCLAIMER OF WARRANTY
 * ----------------------------------------------------------------------------
 * THIS SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 *
 * See accompanying LICENSE and NOTICE files for the integrated terms of use.
 * ============================================================================*
 * @file no_recursion_check.hpp
 * @brief Static Stack and Recursion Control.
 * @details Enforces a flat execution model. By marking functions as Leaf, we
 * allow the compiler to make aggressive assumptions about register usage and
 * memory aliasing, while forbidding re-entry.
 */

#pragma once

  // SLAB_LEAF: The function is a "terminal node" in the execution graph.
  // It cannot call any function defined in the current translation unit or
  // call back into the SLABFLUX core.
#define SLAB_LEAF __attribute__((leaf, nothrow))

// SLAB_PURE: The function's return value depends only on its arguments.
// This allows the compiler to eliminate redundant calls entirely.
#define SLAB_PURE [[gnu::pure]] [[nodiscard]]

// SLAB_FLATTEN: Tells the compiler to inline every single call inside this
// function, effectively turning a call-tree into a single linear instruction block.
#define SLAB_FLATTEN [[gnu::flatten]]

namespace slabflux::compute {

    /**
     * @brief A Logic Unit.
     * @details Every operation on the hot path must be a Leaf function to
     * keep the stack frame size constant and predictable.
     */
    class stack_monitor {
    public:
        /**
         * @brief Compile-time check for stack safety.
         * @note To truly enforce this, add the following to your GCC/Clang flags:
         * -fstack-usage
         * -Wstack-usage=1024
         * -Werror
         */
        template<auto Func>
        static constexpr void verify_terminal() {
            // In a system, we audit the call graph during the CI/CD
            // process using the .su (stack usage) files generated by the compiler.
        }

    /**
     * @brief Compile-Time Pipeline Depth Enforcer.
     * @details Replaces runtime thread-local counters (which cause latency) with 
     * a zero-cost Template Metaprogramming assertion. Enforces absolute graph flatness.
     */
    template <typename T, size_t Depth = 0>
    struct compile_time_depth_analyzer {
        static_assert(Depth < 5, "Deep recursion detected. "
                                 "SlabFlux pipelines must be strictly flat to ensure O(1) determinism.");
        static constexpr bool valid = true;
    };
    };

    /**
     * @brief Example of a terminal compute operation.
     * @details Marked as SLAB_LEAF to ensure the CPU never has to worry
     * about re-entrancy or hidden stack spills.
     */
    SLAB_LEAF SLAB_PURE
        inline double calculate_midpoint(double bid, double ask) noexcept {
        return (bid + ask) * 0.5;
    }

} // namespace slabflux::compute
