/*
 * SPDX-License-Identifier: LicenseRef-SlabFlux-Source-Available
 *
 * ============================================================================
 * SLABFLUX SOFTWARE ENGINE
 * Copyright (c) 2026 Kristóf Barta (https://github.com/kbartadev)
 * ============================================================================
 * SOURCE-AVAILABLE CODEBASE
 *
 * This source file is distributed under the conditions of the SLABFLUX 
 * SOURCE-AVAILABLE AND ECOSYSTEM LICENSE (the "License").
 *
 * ----------------------------------------------------------------------------
 * CRITICAL WARNING
 * ----------------------------------------------------------------------------
 * This module may execute outside standard OS mediation layers. Incorrect 
 * integration, misconfiguration, or unsafe deployment can result in:
 *
 *   • irreversible data corruption
 *   • kernel instability or panics
 *   • NIC or PCIe bus desynchronization
 *   • undefined hardware state transitions
 *   • permanent loss of system integrity
 *
 * Use only in controlled environments with full understanding of the 
 * architectural constraints and hardware implications.
 *
 * ----------------------------------------------------------------------------
 * USAGE GUIDELINES
 * ----------------------------------------------------------------------------
 * Execution, integration, and deployment by developers is permitted strictly 
 * subject to the conditional grants and structural limitations defined within 
 * the License. Please refer to the License for full terms regarding corporate 
 * deployment and replication.
 *
 * ----------------------------------------------------------------------------
 * LIMITATION OF LIABILITY
 * ----------------------------------------------------------------------------
 * TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL THE AUTHOR OR 
 * COPYRIGHT HOLDER BE LIABLE FOR ANY CLAIM, DAMAGES, OR OTHER LIABILITY, 
 * WHETHER IN AN ACTION OF CONTRACT, TORT, OR OTHERWISE, ARISING FROM, OUT OF, 
 * OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 *
 * ----------------------------------------------------------------------------
 * DISCLAIMER OF WARRANTY
 * ----------------------------------------------------------------------------
 * THIS SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 *
 * See accompanying LICENSE and NOTICE files for the integrated terms of use.
 * ============================================================================* @file embedded_certificate.hpp
 * @brief Zero-Syscall X.509 Certificate Accessor.
 */

#pragma once
#include <cstddef>
#include <string_view>
#include "slabflux/core/hot_path_alignment.hpp"

// These symbols are automatically generated by the linker via `objcopy`.
// The exact names are derived from the input filename (e.g., server_cert.der).
extern "C" {
    extern const unsigned char _binary_server_cert_der_start[];
    extern const unsigned char _binary_server_cert_der_end[];
    extern const unsigned char _binary_client_cert_der_start[];
    extern const unsigned char _binary_client_cert_der_end[];
}

namespace slabflux::security {

    struct embedded_certificate {
        /**
         * @brief Returns the statically linked X.509 certificate.
         * @details Resolves exactly to the .rodata segment of the binary,
         * eliminating runtime page faults, heap allocations, and disk I/O.
         */
        static SLAB_FORCE_INLINE std::string_view get_der() noexcept {
            const size_t size = _binary_server_cert_der_end - _binary_server_cert_der_start;
            return std::string_view(reinterpret_cast<const char*>(_binary_server_cert_der_start), size);
        }

        static SLAB_FORCE_INLINE std::string_view get_client_der() noexcept {
            const size_t size = _binary_client_cert_der_end - _binary_client_cert_der_start;
            return std::string_view(reinterpret_cast<const char*>(_binary_client_cert_der_start), size);
        }
    };
}